#!/bin/sh
## V.1.0

if [ $1 ]
  then
  if drush dl $1 -y
    then
    git add -A
    if [ $2 ]
      then
      git commit -m "upgrading $1 module => $2"
      else
        git commit -m "upgrading $1 module"
      fi
    else
      echo "Unable to download module $1"
    fi
  else
  echo "Missing module machine name"
fi
